//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Praktika
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PDDEntities : DbContext
    {
        public PDDEntities()
            : base("name=PDDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Автошколы> Автошколы { get; set; }
        public virtual DbSet<Билеты> Билеты { get; set; }
        public virtual DbSet<Варианты_ответов> Варианты_ответов { get; set; }
        public virtual DbSet<Вопрос> Вопрос { get; set; }
        public virtual DbSet<Обучающиеся> Обучающиеся { get; set; }
        public virtual DbSet<Попытки> Попытки { get; set; }
        public virtual DbSet<Статистика> Статистика { get; set; }
    }
}
