//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Praktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Автошколы
    {
        public byte idAuto { get; set; }
        public string Название { get; set; }
        public Nullable<int> ЦенаКатегорииА { get; set; }
        public Nullable<int> ЦенаКатегорииBМех { get; set; }
        public Nullable<int> ЦенаКатегорииBАвт { get; set; }
        public Nullable<int> ЦенаКатегорииС { get; set; }
        public Nullable<int> ЦенаКатегорииD { get; set; }
        public Nullable<double> Рейтинг { get; set; }
    }
}
