//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Praktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Вопрос
    {
        public byte idQue { get; set; }
        public byte idBilet { get; set; }
        public string Вопрос1 { get; set; }
        public string Подсказка { get; set; }
    
        public virtual Билеты Билеты { get; set; }
    }
}
