//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Praktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Статистика
    {
        public byte idStat { get; set; }
        public byte idStudent { get; set; }
        public Nullable<int> КоличествоПройденныхБилетов { get; set; }
        public Nullable<int> КоличествоНепройденныхБилетов { get; set; }
        public Nullable<int> КоличествоЗатраченногоВремемни { get; set; }
    
        public virtual Обучающиеся Обучающиеся { get; set; }
    }
}
